name: Backend CI Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch: # Allows manual execution

jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pipenv install
        working-directory: backend

      - name: Run ESLint
        run: pipenv run lint
        working-directory: backend

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pipenv install
        working-directory: backend

      - name: Run Test
        run: pipenv run test
        working-directory: backend

  build:
    name: Build Backend Application
    runs-on: ubuntu-latest
    needs: [lint, test] # Only runs if lint and test jobs succeed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t backend-app backend
  deploy:
      name: Deploy to Kubernetes
      runs-on: ubuntu-latest
      needs: build # Only runs if the build job succeeds
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.25.0' # Specify your desired kubectl version

        - name: Apply Kubernetes Manifests
          run: kubectl apply -f k8s/deployment.yaml
          working-directory: backend