name: Backend CI Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: pip install pipenv
        working-directory: backend

      - name: Install Dependencies
        run: pipenv install
        working-directory: backend

      - name: Run ESLint
        run: pipenv run lint
        working-directory: backend

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: pip install pipenv
        working-directory: backend

      - name: Install Dependencies
        run: pipenv install
        working-directory: backend

      - name: Run Test
        run: pipenv run test
        working-directory: backend

  build:
    name: Build Backend Application
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t backend-app backend
